# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleProject
   pod 'Moya', '~> 14.0' 
   pod 'Nuke', '~> 10.7'


  target 'SampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleProjectUITests' do
    # Pods for testing
  end

end
